const BestSellers = [
  {
    id: 1,
    img: "https://api.ecom.longines.com/media/catalog/product/w/a/watch-collection-hydroconquest-l3-781-4-96-6-1685966363.png?w=320",
    name: "hydroconquest",
    radius: 41,
    type: "automatic watch",
    material: "stainless steel and cermaic bezel",
    price: 174000,
  },
  {
    id: 2,
    img: "https://api.ecom.longines.com/media/catalog/product/w/a/watch-collection-the-longines-master-collection-l2-919-4-78-3-1683700202.png?w=320",
    name: "longines master collection",
    radius: 42,
    type: "automatic watch",
    material: "stainless steel",
    price: 259000,
  },
  {
    id: 3,
    img: "https://api.ecom.longines.com/media/catalog/product/w/a/watch-collection-longines-dolcevita-l5-255-4-71-6-1683697208.png?w=320",
    name: "longines dlcevita",
    radius: 20.8 * 32.0,
    type: "quartz watch",
    material: "stainless steel",
    price: 139000,
  },
  {
    id: 4,
    img: "https://api.ecom.longines.com/media/catalog/product/w/a/watch-collection-flagship-heritage-l4-795-4-78-2-1683697096.png?w=320",
    name: "flagship heritage",
    radius: 38.5,
    type: "automatic watch",
    material: "stainless steel",
    price: 180000,
  },
  {
    id: 5,
    img: "https://api.ecom.longines.com/media/catalog/product/w/a/watch-collection-longines-spirit-l3-812-4-63-6-1683699512.png?w=320",
    name: "longines spirit zulu time",
    radius: 42,
    type: "automatic watch",
    material: "stainless steel and ceramic bezels",
    price: 309000,
  },
];
const novelties = [
  {
    id: 1,
    img: "https://api.ecom.longines.com/media/catalog/product/w/a/watch-collection-conquest-heritage-l1-648-4-78-2-1700765141.png?w=560",
    name: "conquest heritage centeral power reserve",
    radius: 38,
    type: "automatic watch",
    material: "stainless steel",
    price: 375000,
  },
  {
    id: 2,
    img: "https://api.ecom.longines.com/media/catalog/product/w/a/watch-collection-longines-legend-diver-l3-764-4-90-6-1698952569.png?w=360",
    name: "longines legend diver",
    radius: 39,
    type: "automatic watch",
    material: "stainless steel",
    price: 322000,
  },
  {
    id: 3,
    img: "https://api.ecom.longines.com/media/catalog/product/w/a/watch-collection-longines-mini-dolcevita-l5-200-0-75-6-1692876894.png?w=560",
    name: "mini dolcevita",
    radius: 29,
    type: "quartz watch",
    material: "stainless steel",
    price: 380000,
  },
  {
    id: 4,
    img: "https://api.ecom.longines.com/media/catalog/product/w/a/watch-collection-longines-spirit-l3-802-5-53-6-1683700745.png?w=560",
    name: "longines spirit zulu time",
    radius: 39,
    type: "automatic watch",
    material: "stainless steel and 18 karat yellow gold cap 200",
    price: 422000,
  },
  {
    id: 5,
    img: "https://api.ecom.longines.com/media/catalog/product/w/a/watch-collection-hydroconquest-l3-790-4-56-6-1689159632.png?w=560",
    name: "hydroconquest gmt",
    radius: 39,
    type: "automatic watch",
    material: "stainless steel and ceramic bezels",
    price: 291000,
  },
];
module.exports = { BestSellers, novelties };
